/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Post = t.iface([], {
  "userId": "number",
  "id": "number",
  "title": "string",
  "body": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Post,
};
export default exportedTypeSuite;
