/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ReqresUser = t.iface([], {
  "id": "number",
  "email": "string",
  "first_name": "string",
  "last_name": "string",
  "avatar": "string",
});

export const ReqresUsersResponse = t.iface([], {
  "page": "number",
  "per_page": "number",
  "total": "number",
  "total_pages": "number",
  "data": t.array("ReqresUser"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ReqresUser,
  ReqresUsersResponse,
};
export default exportedTypeSuite;
